name: Terraform Initialization
description: Initializes and authorizes Terraform
inputs:
  aws-access-key-id:
    description: AWS_ACCESS_KEY_ID
    required: true
  aws-secret-access-key:
    description: AWS_SECRET_ACCESS_KEY
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        #          role-to-assume: arn:aws:iam::493234449900:role/github-terraform-role
        #          role-session-name: githubterraformsession
        aws-region: ${{ env.AWS_REGION }}
    # Installs a specific version of Terraform
    # https://github.com/marketplace/actions/hashicorp-setup-terraform
    # Todo cache Terraform actions/cache@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 0.15.0
    - name: Show Terraform version
      run: terraform --version
      shell: bash
    - name: Terraform init
      run: terraform init
      shell: bash