name: terraform init
author: Jirawat Uttayaya (juttayaya)
description: Initialize and Authorize Terraform

inputs:
  aws-access-key-id:
    description: >-
      AWS Access Key ID. This input is required if running in the GitHub hosted environment.
    required: true
  aws-secret-access-key:
    description: >-
      AWS Secret Access Key. This input is required if running in the GitHub hosted environment.
    required: true
  aws-region:
    description: 'AWS Region, e.g. us-east-2'
    required: true
  terraform-version:
    description: Terraform version to use
    required: false
    default: 1.2.3
  terraform-directory:
    description: Directory where Terraform config is located
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    # Installs a specific version of Terraform
    # https://github.com/marketplace/actions/hashicorp-setup-terraform
    # Todo cache Terraform actions/cache@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform-version }}
    - name: Terraform init
      working-directory: ${{ inputs.terraform-directory }}
      run: terraform init
      shell: bash


