name: Terraform Pull Request
on:
  pull_request:
    types: [opened, edited, reopened]
permissions:
  contents: read    # This is required for actions/checkout
jobs:
  terraform-pr0:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v3
