name: Reusable Workflow Example

on:
  workflow_call:
    inputs:
      varname01:
        required: true
        type: string
      varname02:
        required: false
        type: number

jobs:
  reusable-workflow-job:
    name: Reusable Workflow Job Name
    runs-on: ubuntu-latest
    steps:
      - name: Execute Reusable Step One
        run: echo "Reusable Step One"
      - name: Execute Reusable Step Two
        run: echo "Reusable Step Two with inputs ${{ inputs.varname01 }} and ${{ inputs.varname02 }}"
