name: Reusable Workflow Caller Example

on:
  # workflow_dispatch is a manually invoked workflow
  workflow_dispatch:

jobs:
  reusable-workflow-caller-1A:
    name: 01A Calling Reusable Workflow
    # Use the `uses` keyword to invoke Reusable GitHub Workflows
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      varname01: 01A
  reusable-workflow-caller-2A:
    name: 02A Calling Reusable Workflow
    needs:
      - reusable-workflow-caller-1A
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      varname01: 02A
      varname02: 2
  reusable-workflow-caller-1B:
    name: 01B Calling Reusable Workflow
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      varname01: Caller Input String 01B
      varname02: 1
    # Callers can pass all secrets to reusable workflows via inherit
    secrets: inherit
