name: Terraform Plan
on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'terraform/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read    # This is required for actions/checkout
defaults:
  run:
    working-directory: terraform
env:
  AWS_REGION : "us-east-1"
  terraform-version: 0.15.0
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v3
      - name: Initialize Terraform
        uses: ./.github/actions/terraform-init
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          terraform-version: ${{ env.terraform-version }}
      - name: Terraform init
        run: terraform init
      - name: Terraform plan
        run: terraform plan -no-color
