name: Terraform Plan
on:
  push:
    branches:
      - 'main'
    paths:
      - 'terraform/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read    # This is required for actions/checkout
env:
  AWS_REGION : "us-east-1"
  terraform-version: 1.2.3
  terraform-directory: "terraform"
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v3
      - name: Initialize Terraform
        uses: ./.github/actions/terraform-init
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          terraform-version: ${{ env.terraform-version }}
          terraform-directory: ${{ env.terraform-directory }}
      - name: Terraform plan
        working-directory: ${{ env.terraform-directory }}
        run: terraform plan -no-color -out=github-tf.plan
      - name: Terraform apply
        working-directory: ${{ env.terraform-directory }}
        run: terraform apply -no-color -auto-approve github-tf.plan

